/*
 * generated by Xtext
 */
package org.wsn.sennet.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DSLRuntimeModule extends org.wsn.sennet.xtext.AbstractDSLRuntimeModule {

}
