/*
 * generated by Xtext
 */
package org.wsn.sennet.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DSLUiModule extends org.wsn.sennet.xtext.ui.AbstractDSLUiModule {
	public DSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
