/*
 * generated by Xtext
 */
package org.wsn.sennet.xtext.ui.contentassist

import org.wsn.sennet.xtext.ui.contentassist.AbstractDSLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class DSLProposalProvider extends AbstractDSLProposalProvider {
}
