/**
 *
 * $Id$
 */
package org.wsn.sennet.validation;

import org.eclipse.emf.common.util.EList;

import org.wsn.sennet.AbstractSensor;
import org.wsn.sennet.SinkNode;

import org.wsn.sennet.enums.InterNodeComm;
import org.wsn.sennet.enums.RoutingProtocol;

/**
 * A sample validator interface for {@link org.wsn.sennet.AbstractNetwork}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AbstractNetworkValidator {
	boolean validate();

	boolean validateNbOfNodes(int value);
	boolean validateInterNodeComm(InterNodeComm value);
	boolean validateRoutingProtocol(RoutingProtocol value);
	boolean validateResources(EList<AbstractSensor> value);
	boolean validateSink(SinkNode value);
}
