/**
 *
 * $Id$
 */
package org.wsn.sennet.validation;

import org.eclipse.emf.common.util.EList;

import org.wsn.sennet.AbstractNetwork;
import org.wsn.sennet.AbstractNode;
import org.wsn.sennet.AbstractStartEndingJobTrigger;
import org.wsn.sennet.AbstratAction;

/**
 * A sample validator interface for {@link org.wsn.sennet.AbstractJob}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AbstractJobValidator {
	boolean validate();

	boolean validateJobTargetNode(AbstractNode value);
	boolean validateJobTargetNetwork(AbstractNetwork value);
	boolean validateStartEndTrigger(EList<AbstractStartEndingJobTrigger> value);
	boolean validateJobaction(EList<AbstratAction> value);
}
