/**
 *
 * $Id$
 */
package org.wsn.sennet.validation;

import org.wsn.sennet.enums.LedStatus;
import org.wsn.sennet.enums.Leds;

/**
 * A sample validator interface for {@link org.wsn.sennet.BlinkAction}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BlinkActionValidator {
	boolean validate();

	boolean validateLed(Leds value);
	boolean validateStatus(LedStatus value);
}
