/**
 *
 * $Id$
 */
package org.wsn.sennet.validation;

import org.wsn.sennet.enums.LogicalSymbol;

/**
 * A sample validator interface for {@link org.wsn.sennet.ConditionalAction}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConditionalActionValidator {
	boolean validate();

	boolean validateSensorTerm(String value);
	boolean validateLogicalSymbol(LogicalSymbol value);
	boolean validateValue(long value);
	boolean validateUnit(String value);
}
